apiVersion: v1
kind: Service
metadata:
  name: fc-auth
  namespace: default
  labels:
    app: fc-auth
spec:
  selector:
    app: fc-auth
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30090
  type: NodePort