spring:
  application:
    name: fc-auth
  datasource:
    url: jdbc:mysql://localhost:3313/fc-auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kakao:
  client_id: 1f5c7bef903f764ffa451421371f62de
  redirect_uri: http://localhost:8080/kakao/callback
  client_secret: nZ4fcTGg8rTe1DO8KTiXtn5QXD5lkKYV